name: "Continous Integration pipeline"

concurrency: development

on:
  push:
    branches:
      - main

jobs:
  call-shared-workflow:
    uses: ams-community-github/talkize/.github/workflows/shared-workflow.yml@main
    secrets:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: call-shared-workflow
    environment: development
    env:
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - name: Deploy on development environment
        run: npm run deploy
