name: "Release pipeline"

concurrency:
  group: release
  cancel-in-progress: true

env:
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  push:
    branches:
      - release/*

jobs:
  call-shared-workflow:
    uses: ams-community-github/talkize/.github/workflows/shared-workflow.yml@main
    secrets:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  application-version:
    runs-on: ubuntu-latest
    needs: call-shared-workflow
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - name: Set application version
        run: |
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          BRANCH_VERSION=$(printf '%s\n' ${GIT_BRANCH//release\//})
          TAG_VERSION=$(git tag --list | sort -V | tail -n1)
          export BRANCH_VERSION="${BRANCH_VERSION}" && TAG_VERSION="${TAG_VERSION}" && npm run version
          PATCH_VERSION="$(cat .patch-version)"
          APPLICATION_VERSION=${BRANCH_VERSION}.${PATCH_VERSION}
          echo "APPLICATION_VERSION=$APPLICATION_VERSION" >> $GITHUB_ENV

  deploy-staging:
    needs: application-version
    runs-on: ubuntu-latest
    environment: staging
    env:
      APPLICATION_ENVIRONMENT: "staging"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - name: Deploy on staging environment
        run: npm run deploy

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    env:
      APPLICATION_ENVIRONMENT: "production"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - name: Push tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: ${{ env.APPLICATION_VERSION }}
          git_tag_prefix: "v"
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.APPLICATION_VERSION }}
          name: Release ${{ env.APPLICATION_VERSION }}
      - name: Deploy on production environment
        run: npm run deploy
