name: "Continous Integration pipeline"

concurrency:
  group: release
  cancel-in-progress: true

env:
  AWS_REGION: "us-east-1"

on:
  push:
    branches:
      - release/*

jobs:
  call-shared-workflow:
    uses: ams-community-github/talkize/.github/workflows/shared-workflow.yml@main
    secrets:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  # deploy-rec:
  #   runs-on: ubuntu-latest
  #   environment: rec

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         cache: "npm"
  #     - run: npm ci
  #     - name: Generate Cloudformation
  #       run: npm run deploy

  # deploy-production:
  #   runs-on: ubuntu-latest
  #   environment: production

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         cache: "npm"
  #     - run: npm ci
  #     - name: Generate Cloudformation
  #       run: npm run deploy
